build_gcc10:
  stage: build
  image: ubuntu
  script:
    - apt-get update
    - apt-get install cmake gcc-10 g++-10 -y
    - export CC=gcc-10
    - export CXX=g++-10
    # Build without boost
    - ./build.sh
    # Build with boost
    - apt-get install libboost-test-dev -y
    - cd build
    - cmake ../src/ -DCMAKE_BUILD_TYPE=Release -DCPPINCLUDE_BUILD_WITH_TESTS=ON
    - cmake --build . --config Release
    # Run tests
    - ctest . -C Release
    
build_gcc7:
  stage: build
  image: ubuntu
  script:
    - apt-get update
    - apt-get install cmake gcc-7 g++-7 -y
    - export CC=gcc-7
    - export CXX=g++-7
    # Build without boost
    - ./build.sh
    # Build with boost
    - apt-get install libboost-test-dev -y
    - cd build
    - cmake ../src/ -DCMAKE_BUILD_TYPE=Release -DCPPINCLUDE_BUILD_WITH_TESTS=ON
    - cmake --build . --config Release
    # Run tests
    - ctest . -C Release

build_clang:
  stage: build
  image: ubuntu
  script:
    - apt-get update
    - apt-get install cmake clang -y
    - export CC=/usr/bin/clang
    - export CXX=/usr/bin/clang++
    # Build without boost
    - ./build.sh
    # Build with boost
    - apt-get install libboost-test-dev -y
    - cd build
    - cmake ../src/ -DCMAKE_BUILD_TYPE=Release -DCPPINCLUDE_BUILD_WITH_TESTS=ON
    - cmake --build . --config Release
    # Run tests
    - ctest . -C Release
    
build_windows:
  stage: build
  tags:
    - vm_win
  script:
    #- choco install cmake -y
    - $env:PATH="C:\Program Files\CMake\bin;$env:PATH"
    # Build without boost
    - cmd /c ".\build.bat"
    # Clean build folder
    - rm -r -fo ./build
    - mkdir build
    - cd build
    # Build with boost
    #- vcpkg install boost-test:x64-windows
    #- vcpkg install boost-system:x64-windows
    - cmake ../src/ -G "Visual Studio 16" -DCMAKE_BUILD_TYPE=Release -DCPPINCLUDE_BUILD_WITH_TESTS=ON -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake
    - cmake --build . --config Release
    # Run tests
    - ctest . -C Release
    
build_vs2017:
  stage: build
  tags:
    - vm_win
  script:
    #- choco install visualstudio2017community -y
    #- choco install visualstudio2017-workload-nativedesktop -y
    #- choco install cmake -y
    - $env:PATH="C:\Program Files\CMake\bin;$env:PATH"
    - cd build
    - cmake -G "Visual Studio 15" ../src/ -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --config Release
    
build_macos:
  stage: build
  tags: 
    - macmini
  script:
    # Build without boost
    - ./build.sh
    # Build with boost
    # brew install boost
    - cd build
    - cmake ../src/ -DCMAKE_BUILD_TYPE=Release -DCPPINCLUDE_BUILD_WITH_TESTS=ON
    - cmake --build . --config Release
    # Run tests
    - ctest . -C Release
    
check_typos:
  stage: build
  image: ubuntu
  script:
    - apt-get update
    - export DEBIAN_FRONTEND=noninteractive
    - ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
    - apt-get install -y tzdata
    - dpkg-reconfigure --frontend noninteractive tzdata
    - apt-get install npm -y
    - npm install -g cspell
    - cspell "src/**/*"
    
cppcheck:
  stage: build
  image: ubuntu
  script:
    - apt-get update
    - apt-get install cmake gcc g++ libboost-test-dev -y
    - apt-get install cppcheck -y
    - cd build
    - cmake ../src/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCPPINCLUDE_BUILD_WITH_TESTS=ON
    - cppcheck --project=compile_commands.json --enable=all --suppressions-list=../.cppcheck-suppressions-list --error-exitcode=1 --quiet

